name: Build
on:
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        name: Test
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/kotlin/Library.kt') }}

            - name: Ktlint
              run: ./gradlew ktlintCheck

            - name: Unit Tests
              run: ./gradlew testDebugUnitTest

            - name: Instrumentation Tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 25
                  arch: x86_64
                  script: ./gradlew connectedDebugAndroidTest

            - name: Deploy Snapshot
              if: github.ref == 'master'
              env:
                  SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
                  SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
              run: ./upload_archives.sh
